services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - DB_PORT=5432
      - DB_HOST=db
    command: ["python3", "api.py"]

  db:
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
      - "5431:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
