services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      #- ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    network_mode: host

  data-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime
    #restart: unless-stopped
    logging:
      driver: "json-file"
    environment:
      - PYTHONUNBUFFERED=1
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/i2c-2:/dev/i2c-2"
    command: ["python3", "fetch_data.py"]
    depends_on:
      - mosquitto
    network_mode: host
